### ISSUE TITLE
Profile does not load: "login first" Loop 

### ISSUE THREAD

**Issue by LeandroJardimCH** [MidKnightXI/opgg-ads-remover#21]
**Describe the bug**
After applying the patch, when launching the application OP.GG is unable to load the summoner and asks to connect to the Riot client. 
Even when the Riot client is launched and the user is logged in, the runes etc. are not loaded.

**To Reproduce**
1: Patch OP.GG  with opgg-ads-remover
2: Launch OP.GG (V1.1.21)
3: Lauch Riot Client and login
4: OP.GG is unable to retrieve the Riot account from the client 

**Expected behavior**
Retrieve the Riot account from the client and remove ads in OP.GG

**Screenshots**
![image](https://github.com/MidKnightXI/opgg-ads-remover/assets/52886520/1e8dc4ff-ec5e-487b-801d-019144866803)

![image](https://github.com/MidKnightXI/opgg-ads-remover/assets/52886520/3daefde3-7f02-4b1c-8b08-3d55e7ef4db5)

**Desktop (please complete the following information):**
 - OS: [Windows 11 22h2]
I have done several uninstallations and reinstallations of OP.GG and the Patcher but the problem persists

**Comment by MidKnightXI** [comment]
I'm sorry about all these issues at the moment, it's all due to the svn we are using with Shiyim for our adblocker.

I'll try to work into my own one asap but it's gonna be really complicated over this month.

I'm coming back to my home country next month and will finally have access to a windows machine so I'll be able to work on that project properly FINALLY.

If I find anything that could fix this problem in the meantime I will not hesitate to add a patch.

**Comment by MidKnightXI** [comment]
I don't have this problem on my PC:
![image](https://github.com/MidKnightXI/opgg-ads-remover/assets/35759490/d6ec8260-a1ad-465b-9166-6a832fdab685)

Did you try to reinstall OPGG and patch again?
