### ISSUE TITLE
Client-based app features are not working after the patch is applied

### ISSUE THREAD

**Issue by BVLLISTA** [MidKnightXI/opgg-ads-remover#30]
**Describe the bug**
The League client based app features such as OP.GG pick, multi-search, champion, in-game, etc. don't work after applying the patch. The app stops detecting the status of the League client.

**To Reproduce**
1. Go to OPGG Patcher
2. Apply the patch
3. Run OP.GG
4. Run League Client
5. See the client is not detected by the OPGG app and your profile does not get loaded in to the app.

**Expected behavior**
When the league client is opened, the summoner profile will get loaded in to the OPGG app's main page, and the app features will work properly on champion select and in-game, etc.

**Screenshots**
<img width="1223" alt="Screenshot 2023-07-25 212402" src="https://github.com/MidKnightXI/opgg-ads-remover/assets/107594745/a1f2703b-4581-448a-a8d8-8c706a181562">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OPGG App Version: 1.1.25

**Comment by MidKnightXI** [comment]
I'm currently doing my own cloudflare worker, it might fix the problem.


Release: soon tm

**Comment by MidKnightXI** [comment]
#28

**Comment by MidKnightXI** [comment]
I'm currently doing my own cloudflare worker, it might fix the problem. #28 

Release: soon tm

**Comment by MidKnightXI** [comment]
Quick update:

- I managed to deploy the Cloudflare Worker
- Now blocking some tracking stuff
- Ads are still showing up because ads and live-game features are coming from the same reference: `https://app.labs.sydney`

I'm wondering if I should deploy the next version like that even if there are still ads showing up but the live-game features are enabled and continue to work to improve it with time. Or just leave it as it is today and keep working on it. I think it might take me some time to dig in how to change all of that.

**Comment by MidKnightXI** [comment]
https://github.com/MidKnightXI/opgg-ads-remover/releases/tag/v2.3.0

You can try this version if you want your live features enabled
